import { AlertTriangle, FileCode2, GitCommitHorizontal, LockKeyhole, RefreshCw, ShieldCheck } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api, type ApiEvidence, type ApiProject, ApiError } from '../../api/client';
import { DemoNote, SectionHeading, SourceChip, StrengthLabel } from '../../components/ui';

export default function RealEvidencePage() {
  const [params] = useSearchParams();
  const [projects, setProjects] = useState<ApiProject[]>([]);
  const [projectId, setProjectId] = useState(params.get('projectId') || '');
  const [evidence, setEvidence] = useState<ApiEvidence[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  async function load(nextProjectId = projectId) { setLoading(true); setError(null); try { const nextProjects = await api.projects.list(); setProjects(nextProjects); const selectedId = nextProjectId || nextProjects[0]?.projectId || ''; setProjectId(selectedId); if (selectedId) setEvidence(await api.projects.evidence(selectedId)); else setEvidence([]); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Evidence could not be loaded.'); } finally { setLoading(false); } }
  useEffect(() => { void load(projectId); }, []);
  const selectedProject = projects.find((project) => project.projectId === projectId);
  const bySkill = useMemo(() => new Set(evidence.map((item) => item.skillName)).size, [evidence]);
  return <div className="page-stack"><DemoNote>These are persisted observations from the Spring Boot evidence API. `EVIDENCE_FOUND` is not a verified skill and cannot be changed from this page.</DemoNote><div className="page-header"><div><div className="eyebrow">Backend evidence engine</div><h1>Evidence</h1><p>{selectedProject ? `${selectedProject.fullName} · select a commit-backed project source.` : 'Select an analyzed project to inspect its evidence.'}</p></div><button className="button button-ghost" onClick={() => void load()}><RefreshCw size={15} /> Refresh</button></div>{error && <div className="notice-bar error"><AlertTriangle size={16} /><span>{error}</span></div>}<div className="real-evidence-toolbar"><label>Project<select value={projectId} onChange={(event) => { setProjectId(event.target.value); void load(event.target.value); }}><option value="">Select project</option>{projects.map((project) => <option value={project.projectId} key={project.projectId}>{project.fullName}</option>)}</select></label>{selectedProject && <SourceChip tone="blue">snapshot loaded per analysis job</SourceChip>}</div>{loading ? <div className="panel loading-block"><RefreshCw className="spin" size={18} /> Loading source-backed observations…</div> : <><section className="real-evidence-summary"><div><strong>{evidence.length}</strong><span>persisted observations</span></div><div><strong>{bySkill}</strong><span>normalized skills</span></div><div><strong>{new Set(evidence.map((item) => item.commitSha)).size}</strong><span>immutable snapshots</span></div><div><strong>{new Set(evidence.map((item) => item.sourceType)).size}</strong><span>deterministic source types</span></div></section><section className="real-evidence-grid">{evidence.map((item) => <article className="real-api-evidence-card" key={item.evidenceId}><div className="real-api-card-top"><div className="real-api-skill"><span className="real-api-icon"><FileCode2 size={16} /></span><div><div className="eyebrow">{item.sourceType.replaceAll('_', ' ')}</div><h3>{item.skillName}</h3></div></div><StrengthLabel strength={item.evidenceStrength} /></div><p>{item.observation}</p><div className="real-source-location"><GitCommitHorizontal size={14} /><code>{item.sourceLocation}</code></div><div className="real-api-card-meta"><span><ShieldCheck size={12} />{item.verificationMethod.replaceAll('_', ' ')}</span><span><LockKeyhole size={12} />{item.visibility.toLowerCase().replaceAll('_', ' ')}</span><span>{new Date(item.observedAt).toLocaleDateString()}</span></div><div className="real-api-card-snapshot"><span>commit</span><code>{item.commitSha.slice(0, 12)}</code></div></article>)}{evidence.length === 0 && <div className="panel inline-empty"><FileCode2 size={17} /> No persisted evidence for this project yet. Run an analysis job first.</div>}</section></>}</div>;
}
