import { ArrowRight, Code2, FileCheck2, Github, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { api, type ApiProject, type ApiSkill } from '../../api/client';
import { DemoNote, MetricCard, SectionHeading } from '../../components/ui';

export default function RealOverviewPage() {
  const [projects, setProjects] = useState<ApiProject[]>([]);
  const [skills, setSkills] = useState<ApiSkill[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([api.projects.list(), api.skills.mine()]).then(([nextProjects, nextSkills]) => { setProjects(nextProjects); setSkills(nextSkills); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load your proof workspace.')); }, []);
  const evidenceBacked = skills.filter((skill) => ['EVIDENCE_FOUND', 'PARTIAL', 'VERIFIED'].includes(skill.status)).length;
  return <div className="page-stack"><DemoNote>This is the backend-backed path. Repository, analysis job, snapshot, and evidence data are loaded from Spring Boot, not browser local storage.</DemoNote><div className="page-header page-header-dashboard"><div><div className="eyebrow">Candidate proof workspace</div><h1>Your proof starts with real work.</h1><p>Connect GitHub, choose one repository, and inspect the evidence SkillLink can actually support.</p></div><Link to="/app/projects" className="button button-primary"><Github size={16} /> Manage GitHub</Link></div>{error && <div className="notice-bar error"><ShieldCheck size={16} /><span>{error}</span></div>}<section className="metric-grid"><MetricCard label="Projects" value={projects.length} detail="selected repository sources" icon={<Code2 size={18} />} tone="blue" /><MetricCard label="Evidence-backed skills" value={evidenceBacked} detail="derived from analysis jobs" icon={<FileCheck2 size={18} />} tone="green" /><MetricCard label="Verified skills" value={skills.filter((skill) => skill.status === 'VERIFIED').length} detail="verification is a later policy step" icon={<ShieldCheck size={18} />} tone="purple" /><MetricCard label="Next step" value="GitHub" detail="connect one authorized source" icon={<Sparkles size={18} />} tone="amber" /></section><section className="panel real-start-panel"><SectionHeading eyebrow="First real proof source" title="Choose the repository you want to prove." description="SkillLink will pin the analysis to a commit, redact secrets, inspect manifests/source, and persist evidence." action={<Link to="/app/projects" className="text-action">Open repository flow <ArrowRight size={13} /></Link>} /><div className="real-start-grid"><StartStep number="01" title="Connect GitHub" text="OAuth state and PKCE protect the authorization callback." done={false} /><StartStep number="02" title="Select one repository" text="No automatic ingestion of all repositories." done={projects.length > 0} /><StartStep number="03" title="Analyze a commit" text="Async job states are reported by the API." done={skills.length > 0} /><StartStep number="04" title="Inspect evidence" text="Each observation points to a snapshot and source location." done={skills.length > 0} /></div></section></div>;
}
function StartStep({ number, title, text, done }: { number: string; title: string; text: string; done: boolean }) { return <div className={`real-start-step ${done ? 'done' : ''}`}><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div>{done && <ShieldCheck size={15} />}</div>; }
