import { ArrowRight, CircleHelp, Network, RefreshCw, ShieldCheck, TriangleAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, type ApiSkill, ApiError } from '../../api/client';
import { DemoNote, FreshnessPill, SectionHeading, StatusPill } from '../../components/ui';

function toSkillStatus(status: string): 'SELF_CLAIM' | 'EVIDENCE_FOUND' | 'PARTIAL' | 'VERIFIED' | 'STALE' | 'EXPIRED' | 'NOT_VERIFIED' | 'DISPUTED' { return ['SELF_CLAIM','EVIDENCE_FOUND','PARTIAL','VERIFIED','STALE','EXPIRED','NOT_VERIFIED','DISPUTED'].includes(status) ? status as any : 'EVIDENCE_FOUND'; }
function toFreshness(state: string): 'CURRENT' | 'AGING' | 'STALE' | 'EXPIRED' | 'NOT_APPLICABLE' { return ['CURRENT','AGING','STALE','EXPIRED','NOT_APPLICABLE'].includes(state) ? state as any : 'NOT_APPLICABLE'; }
export default function RealSkillsPage() {
  const [skills, setSkills] = useState<ApiSkill[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { setSkills(await api.skills.mine()); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Skills could not be loaded.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  return <div className="page-stack"><DemoNote>The real skill graph currently contains only candidate → normalized skill → evidence state. Examination and verification nodes remain intentionally pending until this engine is trusted.</DemoNote><div className="page-header"><div><div className="eyebrow">Backend skill projection</div><h1>Skills</h1><p>Normalized from persisted source evidence. No uncontrolled labels and no opaque confidence percentage.</p></div><button className="button button-ghost" onClick={() => void load()}><RefreshCw size={15} /> Refresh</button></div>{error && <div className="notice-bar error"><TriangleAlert size={16} />{error}</div>}<section className="skill-hero"><div className="skill-hero-copy"><div className="skill-hero-icon"><Network size={22} /></div><div><div className="eyebrow">Living graph · backend state</div><h2>Observed capability has a traceable path.</h2><p>Each row is derived from evidence persisted against a repository snapshot. This milestone does not promote evidence to verification.</p></div></div><div className="skill-hero-stats"><div><strong>{skills.filter((skill) => skill.status === 'EVIDENCE_FOUND').length}</strong><span>evidence found</span></div><div><strong>{skills.reduce((sum, skill) => sum + skill.evidenceCount, 0)}</strong><span>evidence items</span></div></div></section><section className="panel real-skill-table"><SectionHeading eyebrow="Normalized taxonomy" title="Your detected skills" action={<Link to="/app/evidence" className="text-action">Inspect evidence <ArrowRight size={13} /></Link>} />{loading ? <div className="loading-block"><RefreshCw className="spin" size={17} /> Loading skill projection…</div> : skills.length === 0 ? <div className="inline-empty"><CircleHelp size={17} /> Analyze a repository before skills appear here.</div> : <div className="real-skill-rows">{skills.map((skill) => <div className="real-skill-row" key={skill.skillId}><div className="real-skill-name"><span className="real-skill-dot" /><div><strong>{skill.name}</strong><small>{skill.category} · normalized key {skill.key}</small></div></div><StatusPill status={toSkillStatus(skill.status)} small /><FreshnessPill state={toFreshness(skill.freshnessState)} /><span className="real-skill-count">{skill.evidenceCount} evidence</span><ShieldCheck size={15} className="real-skill-icon" /></div>)}</div>}</section></div>;
}
