import { Download, Filter, LockKeyhole, Search, SlidersHorizontal, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { DemoNote, EvidenceCard, SectionHeading, SourceChip } from '../components/ui';
import { useStore } from '../store';

export default function EvidencePage() {
  const { evidence, project } = useStore();
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'ALL' | 'DIRECT' | 'STRONG'>('ALL');
  const visible = useMemo(() => evidence.filter((item) => (filter === 'ALL' || item.strength === filter) && `${item.skillName} ${item.location} ${item.observation}`.toLowerCase().includes(query.toLowerCase())), [evidence, filter, query]);
  return <div className="page-stack"><DemoNote>Observation and judgment stay separate. These cards show what the snapshot contains; verification only comes later through policy, defense, and practical proof.</DemoNote><div className="page-header"><div><div className="eyebrow">Evidence engine</div><h1>Evidence</h1><p>Inspectable observations from {project.name}, pinned to <code>{project.repository.commitLabel}</code>.</p></div><button className="button button-ghost"><Download size={15} /> Export summary</button></div><section className="evidence-overview"><div className="evidence-overview-main"><div className="evidence-orbit"><div className="orbit-center"><Sparkles size={18} /><strong>{evidence.length}</strong><span>observations</span></div><span className="orbit-dot orbit-dot-one" /><span className="orbit-dot orbit-dot-two" /><span className="orbit-dot orbit-dot-three" /></div><div><div className="eyebrow">Source-backed signals</div><h2>Every card answers who, what, where, and when.</h2><p>SkillLink starts with deterministic repository facts, then adds bounded interpretation with source references. No unexplained “Java = 90%” scores.</p><div className="source-chip-row"><SourceChip tone="blue">{project.repository.commitLabel} snapshot</SourceChip><SourceChip>7 normalized skills</SourceChip><SourceChip tone="purple">0 secret-like values sent</SourceChip></div></div></div><div className="evidence-overview-side"><div><strong>6</strong><span>direct or strong</span></div><div><strong>1</strong><span>moderate</span></div><div><strong>4</strong><span>source types</span></div></div></section><section className="evidence-section"><SectionHeading eyebrow="Traceability" title="Observed evidence" description="Filter by strength or search a source location." action={<div className="evidence-toolbar"><div className="search-input"><Search size={15} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search evidence" /></div><button className={`filter-button ${filter === 'DIRECT' ? 'active' : ''}`} onClick={() => setFilter(filter === 'DIRECT' ? 'ALL' : 'DIRECT')}><Filter size={14} /> Direct</button><button className={`filter-button ${filter === 'STRONG' ? 'active' : ''}`} onClick={() => setFilter(filter === 'STRONG' ? 'ALL' : 'STRONG')}><SlidersHorizontal size={14} /> Strong</button></div>} /><div className="evidence-grid">{visible.map((item) => <EvidenceCard evidence={item} key={item.id} />)}</div>{visible.length === 0 && <div className="inline-empty"><LockKeyhole size={17} /> No evidence matches this filter. Try a broader search.</div>}</section></div>;
}
