import { ArrowRight, Check, ChevronRight, Code2, FileCheck2, Fingerprint, Github, GraduationCap, LockKeyhole, Play, ShieldCheck, Sparkles, Users, Waypoints } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Logo } from '../components/ui';

export default function LandingPage() {
  return <div className="landing-page">
    <nav className="landing-nav"><Link to="/" className="landing-logo"><Logo /></Link><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#for-recruiters">For recruiters</a><a href="#for-colleges">For colleges</a></div><div className="landing-actions"><Link to="/signin" className="landing-signin">Sign in</Link><Link to="/signin" className="button button-primary button-small">Build my proof <ArrowRight size={15} /></Link></div></nav>
    <main>
      <section className="hero-section"><div className="hero-glow hero-glow-left" /><div className="hero-glow hero-glow-right" /><div className="hero-content"><div className="hero-kicker"><span className="live-pulse" />The proof layer for modern work</div><h1>Don't claim your skills.<br /><span>Prove them.</span></h1><p className="hero-subtitle">Turn your real work into evidence-backed, verified capability that recruiters can actually inspect.</p><div className="hero-cta"><Link to="/signin" className="button button-primary button-large">Build my proof <ArrowRight size={17} /></Link><a href="#how-it-works" className="button button-ghost button-large"><Play size={15} /> See how it works</a></div><div className="hero-trust"><span><ShieldCheck size={15} /> Evidence-first by design</span><span><LockKeyhole size={14} /> Private by default</span><span><Github size={15} /> GitHub source</span></div></div><div className="hero-visual" aria-label="Proof graph preview"><div className="hero-visual-top"><span className="window-dot dot-red" /><span className="window-dot dot-yellow" /><span className="window-dot dot-green" /><span className="hero-window-title">proof / foodbridge-api</span><span className="hero-window-lock"><LockKeyhole size={12} /> private summary</span></div><div className="proof-preview"><div className="preview-sidebar"><div className="preview-sidebar-line active" /><div className="preview-sidebar-line" /><div className="preview-sidebar-line" /><div className="preview-sidebar-line short" /></div><div className="preview-main"><div className="preview-main-head"><div><span className="preview-overline">PROJECT SNAPSHOT</span><strong>FoodBridge API</strong></div><span className="preview-commit"><span className="commit-dot" />abc1234</span></div><div className="preview-grid"><div className="preview-node node-project"><Code2 size={15} /><span>Real project</span><strong>FoodBridge API</strong></div><div className="preview-connector connector-one" /><div className="preview-node node-evidence"><FileCheck2 size={15} /><span>Evidence</span><strong>JwtService.java</strong></div><div className="preview-connector connector-two" /><div className="preview-node node-verified"><ShieldCheck size={16} /><span>Capability</span><strong>JWT Authentication</strong><em>VERIFIED</em></div></div><div className="preview-foot"><span><Check size={12} /> source-backed</span><span><Check size={12} /> project defense</span><span><Check size={12} /> practical task</span></div></div></div></div></section>
      <section className="proof-strip"><div><span className="proof-strip-label">From a claim</span><strong>“I know Spring Boot.”</strong></div><div className="strip-arrow"><ArrowRight size={18} /></div><div className="proof-strip-highlight"><span className="proof-strip-label">To inspectable proof</span><strong>Project · evidence · defense · task</strong></div></section>
      <section className="landing-section" id="how-it-works"><div className="section-center-heading"><span className="eyebrow">The proof loop</span><h2>Capability should be inspectable.</h2><p>SkillLink follows the work, not the words. Every status has a source, a method, and a date.</p></div><div className="steps-grid"><Step number="01" icon={<Github size={19} />} title="Connect real work" text="Start with a repository, project, or other source you control. Private code stays private." /><Step number="02" icon={<FileCheck2 size={19} />} title="Extract evidence" text="Deterministic analyzers locate the implementation before AI interprets what it means." /><Step number="03" icon={<Sparkles size={19} />} title="Defend your work" text="Answer questions grounded in your own files, decisions, trade-offs, and edge cases." /><Step number="04" icon={<Fingerprint size={19} />} title="Share portable proof" text="Package verified capabilities into a recruiter-ready passport with granular visibility." /></div></section>
      <section className="landing-section pillars-section"><div className="section-split-heading"><div><span className="eyebrow">Built around proof</span><h2>Everything else supports the loop.</h2></div><p>SkillLink is not another profile, course marketplace, or opaque talent score. The unit of trust is evidence.</p></div><div className="pillars-grid"><Pillar icon={<Waypoints size={20} />} eyebrow="01 / Living skill graph" title="See the path from person to proof." text="Connect skills to projects, file-level observations, examinations, practical tasks, freshness, and job requirements." /><Pillar icon={<Sparkles size={20} />} eyebrow="02 / AI Proof Examiner" title="Questions from what you actually built." text="A bounded defense probes code locations, architecture, security, debugging, and modification ability." /><Pillar icon={<BriefcaseIcon />} eyebrow="03 / Job → Proof Compiler" title="Turn a JD into an inspectable contract." text="Normalize requirements into proof rows instead of hiding hiring decisions behind a match percentage." /><Pillar icon={<Fingerprint size={20} />} eyebrow="04 / Proof Passport" title="Share what is verified, not everything you own." text="Public summaries can show the capability and its provenance without exposing a private repository." /></div></section>
      <section className="human-ai-section"><div className="human-ai-copy"><span className="eyebrow">Human + AI</span><h2>AI can help you build it.<br /><span>You still have to own it.</span></h2><p>SkillLink does not play an arms race against AI tools. It verifies whether a person can understand, review, test, correct, and explain the final work.</p><Link to="/signin" className="text-link">See the proof model <ArrowRight size={14} /></Link></div><div className="human-ai-card"><div className="human-ai-line"><span className="line-label">Task</span><strong>Fix expired JWT access</strong></div><div className="human-ai-line"><span className="line-label">Assistance</span><strong className="muted-strong">AI suggestion reviewed</strong><Check size={16} /></div><div className="human-ai-line"><span className="line-label">Decision</span><strong>Rejected unsafe refresh flow</strong><Check size={16} /></div><div className="human-ai-line"><span className="line-label">Proof</span><strong>Regression test passes</strong><ShieldCheck size={16} /></div></div></section>
      <section className="landing-section role-section" id="for-recruiters"><div className="role-card role-card-dark"><div className="role-icon"><Users size={21} /></div><span className="eyebrow">For recruiters</span><h3>Review proof, not promises.</h3><p>Translate a job description into required capabilities, inspect the evidence behind each row, and request a targeted proof gap when it matters.</p><Link to="/signin?role=recruiter" className="button button-outline">Explore recruiter view <ArrowRight size={15} /></Link></div><div className="role-card role-card-light" id="for-colleges"><div className="role-icon role-icon-light"><GraduationCap size={21} /></div><span className="eyebrow">For colleges</span><h3>Make practical growth visible.</h3><p>See which students have observable capability, where departments have gaps, and who is ready for a proof-based placement conversation.</p><Link to="/signin" className="text-link">Talk to SkillLink <ArrowRight size={14} /></Link></div></section>
      <section className="final-cta"><div className="final-cta-mark"><ShieldCheck size={27} /></div><span className="eyebrow">Your work deserves evidence</span><h2>Make your capability<br /><span>easy to inspect.</span></h2><Link to="/signin" className="button button-primary button-large">Build my proof <ArrowRight size={17} /></Link><small>Demo workspace available · no GitHub access required</small></section>
    </main>
    <footer className="landing-footer"><Logo /><span>© 2026 SkillLink. The verification layer between work and opportunity.</span><div><a href="#how-it-works">Product</a><a href="#for-recruiters">For teams</a><a href="mailto:hello@skilllink.example">Contact</a></div></footer>
  </div>;
}

function Step({ number, icon, title, text }: { number: string; icon: React.ReactNode; title: string; text: string }) {
  return <div className="step-card"><span className="step-number">{number}</span><div className="step-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>;
}
function Pillar({ icon, eyebrow, title, text }: { icon: React.ReactNode; eyebrow: string; title: string; text: string }) {
  return <div className="pillar-card"><div className="pillar-icon">{icon}</div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3><p>{text}</p><ChevronRight className="pillar-arrow" size={17} /></div>;
}
function BriefcaseIcon() { return <BriefcaseGlyph />; }
function BriefcaseGlyph() { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5.5A1.5 1.5 0 0 1 9.5 4h5A1.5 1.5 0 0 1 16 5.5V7M3 12h18M10 12v2h4v-2"/></svg>; }
