import { Activity, ArrowRight, CheckCircle2, Clock3, Code2, FileCheck2, Fingerprint, GitBranch, GitCommitHorizontal, MoreHorizontal, ShieldCheck, Sparkles, Target, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import { DemoNote, FreshnessPill, MetricCard, SectionHeading } from '../components/ui';
import { SkillList } from '../components/SkillTable';
import { ProofRail } from '../components/ProofRail';
import { useStore } from '../store';

export default function OverviewPage() {
  const { candidate, project, skills, evidence, examination, challenge, githubConnected, analysisNotice } = useStore();
  const verified = skills.filter((skill) => skill.status === 'VERIFIED');
  const evidenceBacked = skills.filter((skill) => ['VERIFIED', 'EVIDENCE_FOUND', 'PARTIAL'].includes(skill.status));
  return <div className="page-stack">
    <DemoNote>Real integrations are represented by production contracts; this workspace is deterministic and local, so the proof loop is safe to explore.</DemoNote>
    <div className="page-header page-header-dashboard"><div><div className="eyebrow">Monday, 28 September 2026</div><h1>Good morning, {candidate.name.split(' ')[0]}.</h1><p>Keep turning the work you have done into proof someone else can trust.</p></div><div className="page-header-actions"><Link to="/app/projects" className="button button-primary"><GitBranch size={16} /> Add a project</Link><Link to="/app/passport" className="button button-ghost"><Fingerprint size={16} /> View passport</Link></div></div>
    {analysisNotice && <div className="notice-bar"><Activity size={16} /><span>{analysisNotice}</span><button aria-label="Dismiss notice">×</button></div>}
    <section className="metric-grid"><MetricCard label="Verified skills" value={verified.length} detail={`of ${skills.length} in your proof graph`} icon={<ShieldCheck size={18} />} tone="green" action={<Link to="/app/skills" className="metric-link">View <ArrowRight size={13} /></Link>} /><MetricCard label="Evidence items" value={evidence.length} detail="across 1 analyzed project" icon={<FileCheck2 size={18} />} tone="blue" action={<Link to="/app/evidence" className="metric-link">Inspect <ArrowRight size={13} /></Link>} /><MetricCard label="Proof readiness" value={`${candidate.verificationProgress}%`} detail="up 12% this week" icon={<TrendingUp size={18} />} tone="purple" /><MetricCard label="Freshness" value="Current" detail="5 capabilities need no refresh" icon={<Clock3 size={18} />} tone="amber" action={<FreshnessPill state="CURRENT" />} /></section>
    <div className="content-with-rail"><div className="main-column">
      <section className="panel project-spotlight"><SectionHeading eyebrow="Active proof path" title="FoodBridge API" description="Your most recent project snapshot and the next verification action." action={<Link to="/app/projects" className="text-action">Open project <ArrowRight size={13} /></Link>} /><div className="project-spotlight-body"><div className="project-identity"><div className="project-logo"><Code2 size={22} /></div><div><h3>{project.name}</h3><p>{project.repository.fullName} <span className="dot-separator">·</span> {project.repository.commitLabel}</p><div className="project-tags"><span>Java</span><span>Spring Boot</span><span>PostgreSQL</span></div></div></div><div className="project-status-block"><span className="eyebrow">Snapshot status</span><div className={`analysis-status analysis-${project.analysisStatus.toLowerCase()}`}><span className="analysis-status-dot" />{project.analysisStatus === 'COMPLETED' ? 'Analyzed' : project.analysisStatus === 'PROCESSING' ? 'Analyzing' : githubConnected ? 'Connected' : 'Not connected'}</div><small>{project.analyzedAt ?? 'Connect a source to begin'}</small></div></div><div className="project-progress"><div className="project-progress-copy"><span>{project.completedStages}/{project.analysisStages.length} analysis stages complete</span><span>{project.analysisStatus === 'COMPLETED' ? 'Evidence ready' : 'Next: inspect source'}</span></div><div className="progress-track"><span style={{ width: `${(project.completedStages / project.analysisStages.length) * 100}%` }} /></div></div></section>
      <section className="panel"><SectionHeading eyebrow="What changed" title="Recent proof activity" action={<Link to="/app/evidence" className="text-action">View all <ArrowRight size={13} /></Link>} /><div className="activity-list"><ActivityRow icon={<FileCheck2 size={16} />} tone="blue" title="Evidence mapped to JWT Authentication" detail="JwtService.java · direct implementation" time="12 min ago" /><ActivityRow icon={<Sparkles size={16} />} tone="purple" title="Project defense is ready" detail="3 questions grounded in FoodBridge API" time="18 min ago" /><ActivityRow icon={<GitCommitHorizontal size={16} />} tone="green" title="Repository snapshot captured" detail={`main · ${project.repository.commitLabel}`} time="24 min ago" /></div></section>
      <section className="panel skill-panel"><SectionHeading eyebrow="Your graph, at a glance" title="Capabilities in motion" description="Statuses are policy outputs, not opaque scores." action={<Link to="/app/skills" className="text-action">Open skill graph <ArrowRight size={13} /></Link>} /><SkillList skills={skills.slice(0, 5)} /></section>
    </div><ProofRail skills={skills} /></div>
    <section className="next-actions"><div className="next-actions-head"><div><div className="eyebrow">Suggested next actions</div><h2>Close one proof gap.</h2></div><Target size={20} /></div><div className="next-actions-grid"><ActionCard number="01" title="Complete project defense" text="Answer 3 questions about your JWT implementation." state={examination.status === 'COMPLETED' ? 'Completed' : '10 min'} link="/app/examiner" icon={<Sparkles size={17} />} /><ActionCard number="02" title="Pass the practical task" text="Add role authorization and explain the regression test." state={challenge.status === 'PASSED' ? 'Passed' : '15–20 min'} link="/app/examiner#practical" icon={<Code2 size={17} />} /><ActionCard number="03" title="Share your passport" text="Give a recruiter an inspectable view of your verified work." state="Ready" link="/app/passport" icon={<Fingerprint size={17} />} /></div></section>
  </div>;
}

function ActivityRow({ icon, tone, title, detail, time }: { icon: React.ReactNode; tone: string; title: string; detail: string; time: string }) { return <div className="activity-row"><span className={`activity-icon activity-${tone}`}>{icon}</span><div className="activity-copy"><strong>{title}</strong><span>{detail}</span></div><time>{time}</time><MoreHorizontal size={16} className="muted-icon" /></div>; }
function ActionCard({ number, title, text, state, link, icon }: { number: string; title: string; text: string; state: string; link: string; icon: React.ReactNode }) { return <Link to={link} className="action-card"><div className="action-card-top"><span className="action-number">{number}</span><span className="action-icon">{icon}</span></div><h3>{title}</h3><p>{text}</p><div className="action-card-bottom"><span>{state}</span><ArrowRight size={14} /></div></Link>; }
