import { ArrowLeft, Check, ExternalLink, Fingerprint, LockKeyhole, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useStore } from '../store';
import { FreshnessPill, Logo, StatusPill } from '../components/ui';

export default function VerifyPage() {
  const { candidate, skills, project } = useStore();
  const { proofId } = useParams();
  const verifiedSkills = skills.filter((skill) => skill.status === 'VERIFIED');
  return <div className="verify-page"><header className="verify-header"><Link to="/"><Logo /></Link><div className="verify-header-right"><span><LockKeyhole size={13} /> Public summary · source protected</span><Link to="/signin" className="button button-ghost button-small">Create your passport <ExternalLink size={14} /></Link></div></header><main className="verify-main"><Link to="/" className="back-link"><ArrowLeft size={14} /> Back to SkillLink</Link><div className="verify-card"><div className="verify-card-top"><div className="passport-seal"><Fingerprint size={27} /></div><div><div className="eyebrow">Verified Proof Passport</div><h1>{candidate.name}</h1><p>{candidate.headline} · {candidate.location}</p></div><div className="verified-stamp"><ShieldCheck size={16} /> Authentic passport</div></div><div className="verify-id-row"><span>Proof ID <code>{proofId ?? 'SL-PASSPORT-AG-2026'}</code></span><span>Issued 28 Sep 2026</span></div><div className="verify-summary"><div><span className="eyebrow">Proof summary</span><h2>Capability with a traceable path.</h2><p>This public view shows verified capability and high-level provenance. Private repository source and assessment answers are not exposed.</p></div><div className="verify-summary-stat"><strong>{verifiedSkills.length}</strong><span>verified skills</span></div><div className="verify-summary-stat"><strong>3</strong><span>proof methods</span></div></div><div className="verify-skills"><div className="verify-section-title"><span>Verified capabilities</span><span>Freshness</span></div>{verifiedSkills.map((skill) => <div className="verify-skill-row" key={skill.id}><div className="verify-skill-name"><span className="verify-check"><Check size={13} /></span><div><strong>{skill.name}</strong><small>{skill.category} · {skill.evidenceCount} accepted evidence items</small></div></div><FreshnessPill state={skill.freshness} /></div>)}</div><div className="verify-provenance"><div><div className="eyebrow">Provenance</div><strong>FoodBridge API · {project.repository.commitLabel}</strong><p>Repository observations, project defense, and policy evaluation recorded against an immutable snapshot.</p></div><StatusPill status="VERIFIED" small /></div><div className="verify-footer"><span><ShieldCheck size={14} /> Verification policy v0.1-demo</span><span>SkillLink is a verification layer, not a hiring decision.</span></div></div><p className="verify-disclaimer">This page is a public summary. To request more detail, the holder must explicitly share additional proof.</p></main></div>;
}
